name: "Push images on merge to master"
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-arch: ["amd64", "arm64", "ppc64le", "s390x"]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
    - name: Display Go version
      run: go version
    - name: build binary
      run: |
        GOARCH=${{ matrix.target-arch }} make spdkcsi
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v6
      with:
        context: _out
        push: true
        platforms: linux/${{ matrix.target-arch }}
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.target-arch }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: ./deploy/image/Dockerfile
  push-manifest:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    needs: [build-and-push-image]
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push manifest for multi-arch images
      run: |
        docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
        ${{ env.IMAGE_NAME }}:${{ github.sha }}-amd64 \
        ${{ env.IMAGE_NAME }}:${{ github.sha }}-arm64 \
        ${{ env.IMAGE_NAME }}:${{ github.sha }}-ppc64le \
        ${{ env.IMAGE_NAME }}:${{ github.sha }}-s390x
